### ISSUE TITLE
Error in main.tf

### ISSUE THREAD

**Issue by MendelD** [fortytwoservices/terraform-azuread-entitlement-management#105]
Hi,

I just encountered an error with this module, when setting "approval_required" to false in configuration I was still required to provide "primary_approver_subject_type" which is a part of "approval_stage" in main.tf, line 60-84.

This caused issues like (if the setting was not provided):
│ The argument
│ "approval_settings.0.approval_stage.0.primary_approver.0.subject_type" is
│ required, but no definition was found.

And (if provided):
│ AccessPackageAssignmentPolicyClient.BaseClient.Post(): unexpected status 400 with OData error: InvalidApprovalStages: If approval is required, a valid list of stages must be provided.

I fixed this issue by changing line 61 from:
for_each = toset(each.value.approval_required != null ? [1] : [])

to:
for_each = toset(each.value.approval_required ? [1] : [])

Seems like != null forced the value to be true, thus triggering approvalstages.

Best regards
Tom Aril Virak

**Comment by sGrindvoll** [comment]
You are correct, the conditional checking if the value is not equal to "null" forced it to be true. This is because the input variable defaults to true, and will never be "null". It would be "null" if it didn't have an default value, and no value was provided in the module call. So good catch!

**Comment by sGrindvoll** [comment]
Fix merged in #106
